name: Build and Publish Python Wheels

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build wheels on ${{ matrix.build.os }}
    runs-on: ${{ matrix.build.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        build:
          - os: ubuntu-24.04
            mamba: git uv cmake cxx-compiler
            cmake: ""
          - os: macos-15
            # use system clang
            mamba: git uv cmake
            cmake: ""
          - os: windows-2022
            mamba: git uv cmake cxx-compiler
            cmake: ""
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: true
          cache-downloads: false
          environment-name: ci
          create-args: ${{ matrix.build.mamba }}
          init-shell: bash
          post-cleanup: 'all'

      - name: build wheels and sdist
        env:
          CMAKE_ARGS: ${{ matrix.build.cmake }}
        run: |
          echo "Building sdist for Python"

          uv build --sdist --python "${ver}" -o wheelhouse/ .

          for ver in ${{ vars.PYTHON_VERSIONS }}; do
            echo "Building wheels for Python ${ver}"

            uv build --wheel --python "${ver}" -o dist/ .
          done

      - name: repair wheels (linux)
        if: matrix.build.os == 'ubuntu-24.04'
        run: |
          uvx auditwheel repair --exclude libggml* -w wheelhouse/ dist/*

      - name: repair wheels (macos)
        if: matrix.build.os == 'macos-15'
        run: |
          uvx delocate-wheel --require-archs arm64 -w wheelhouse/ -v dist/*

      - name: repair wheels (windows)
        if: matrix.build.os == 'windows-2022'
        run: |
          uvx delvewheel repair --ignore-existing -w wheelhouse/ dist/*

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: base-${{ matrix.build.os }}-${{ strategy.job-index }}
          path: wheelhouse/*

  upload_pypi:
    needs: build
    runs-on: ubuntu-24.04
    environment: pypi
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: base-*
          path: dist
          merge-multiple: true

      - name: publish package
        uses: pypa/gh-action-pypi-publish@release/v1
