name: Build and Publish Python Wheels (CUDA)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CUDA_VERSION: "12.8.1"
  PYTHON_VERSIONS: "3.10 3.11 3.12 3.13"

jobs:
  build:
    name: Build wheels on ${{ matrix.build.os }}
    runs-on: ${{ matrix.build.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        build:
          - os: ubuntu-24.04
            cmake: "-DGGML_CUDA=ON -DGGML_CUDA_FORCE_MMQ=ON"
          - os: windows-2022
            cmake: "-DGGML_CUDA=ON -DGGML_CUDA_FORCE_MMQ=ON"
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: true
          cache-downloads: false
          environment-name: ci
          create-args: >-
            git
            uv
            cmake
            cxx-compiler
            cuda==${{ env.CUDA_VERSION }}
            cuda-nvcc
          init-shell: >-
            bash
            powershell
          post-cleanup: 'all'

      - name: build wheels and sdist
        env:
          CMAKE_ARGS: ${{ matrix.build.cmake }}
        run: |
          for ver in ${{ env.PYTHON_VERSIONS }}; do
            uv build --python "${ver}" . -Cwheel.build-tag="1cu${{ env.CUDA_VERSION }}"
          done

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cuda-${{ matrix.build.os }}-${{ strategy.job-index }}
          path: dist/*

  upload_pypi:
    needs: build
    runs-on: ubuntu-24.04
    environment: pypi
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: cuda-*
          path: dist
          merge-multiple: true

      - name: publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
